# server端口号
server:
  port: 18081

spring:
  main:
    banner-mode: off  # Spring boot的logo不显示
  datasource: #配置数据库相关
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://133.65.150.169:8921/rpacc?serverTimezone=UTC
    username: rpacc_user
    password: LC$fwGI61Iq!OwsC
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  global-config:
    banner: off # MybatisPlus的logo不显示
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl